### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Hubbitus** [anapsix/docker-webdis#2]
docker-compose service:
```
  webdis:
    image: anapsix/webdis:latest
    env_file:
      - "../env/${ENV_NAME}/globals.env"
    links:
      - "redis"
    restart: always
```
globals.env:
```
ENV_FULLNAME=rr-psko-master
TZ=Europe/Moscow
```
Crashed after some seconds near start:
```
# d logs -f rrpskomaster_webdis_1
writing config..
taking a 3 second nap..
3 2 1 starting webdis..
tail: can't open '/webdis.log': No such file or directory
[13] 11 Jan 13:56:50 35 Webdis 0.1.4-dev up and running
tail: /webdis.log has appeared; following end of new file
[13] 11 Jan 13:57:01 0 /SUBSCRIBE/user_assignment_taskgbu
[13] 11 Jan 13:57:01 0 /SUBSCRIBE/user_new_taskgbu
[13] 11 Jan 13:57:01 0 /SUBSCRIBE/group_bpm_user
[13] 11 Jan 13:57:01 0 /SUBSCRIBE/group_empl_gbu
Segmentation fault (core dumped)
```
